name: Deploy preview

on:
  pull_request:
    branches:
      - main

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Run yarn install
      - name: ğŸ”© Installing
        run: yarn
        shell: bash

      # Create env file
      - name: ğŸ“ Create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env
          echo NEXT_PUBLIC_MAIL_SERVICE_ID=${{ secrets.NEXT_PUBLIC_MAIL_SERVICE_ID }} >> .env
          echo NEXT_PUBLIC_MAIL_TEMPLATE_ID=${{ secrets.NEXT_PUBLIC_MAIL_TEMPLATE_ID }} >> .env
          echo NEXT_PUBLIC_MAIL_USER_ID=${{ secrets.NEXT_PUBLIC_MAIL_USER_ID }} >> .env

      # Install Netlify CLI
      - name: ğŸ› ï¸ Install Netlify CLI
        run: |
          yarn global add netlify-cli

      # Deploy to Netlify using our dev secrets
      - name: ğŸš€ Build and Deploy to Netlify
        id: deploy-netlify
        run: |
          netlify deploy --alias="$PR_NUMBER" --build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
